### ISSUE TITLE
Using Events 8 bit words with Online PSTH

### ISSUE THREAD

**Issue by guilhemibos** [open-ephys-plugins/online-psth#2]
Hello

I've opened this discussion on the google group. I'd like to to trigger online PSTH based on a specific combination of events (i.e. a specific 8 bit words), and not based on a specific event channel (a single TTL). It seems pretty easy (`event->getWord()` instead of `event->getLine()` on line 113 of OnlinePSTH.cpp,) and increase the available triggers to 256. 
I tried to do it myself but I failed the compilation part... Can you do it for me please?

Thanks
Guilhem

**Comment by jsiegle** [comment]
Here's a version of the Online PSTH plugin with those changes implemented: [online-psth-with-ttl-word-triggers.zip](https://github.com/open-ephys-plugins/online-psth/files/9492345/online-psth-with-ttl-word-triggers.zip)

Also, we'd be happy to help troubleshoot the compilation errors if you can describe what's going wrong.

**Comment by guilhemibos** [comment]
Hey

Thanks a lot. It works perfectly as expected. 
Concerning the compilation troubleshooting, I think it's more me having 0 experience and knowledge about Visual Studio and the world of compiling apps... I can try by I am not even sure I'm able to describe the process appropriately.
I've cloned the GUI is in my GitHub folder:
...\GitHub\plugin-GUI\
I've compiled the open-ephys-GUI properly (at least without errors).

The module is cloned here:
...\GitHub\OEPlugins\online-psth\

I've opened OE_PLUGIN_online-psth.sln in visual studio.  When I select Release and start building a solution, it ends up with this error:
Error	LNK1181	cannot open input file '...\GitHub\OEPlugins\online-psth\..\..\plugin-GUI\Build\Release\open-ephys.lib'	online-psth	...\GitHub\OEPlugins\online-psth\Build\LINK	1	

If I try to debug, it ends up with this:
4>------ Skipped Build: Project: INSTALL, Configuration: Debug x64 ------
4>Project not selected to build for this solution configuration 
========== Build: 3 succeeded, 0 failed, 0 up-to-date, 1 skipped ==========

So I don't know what to do with this:
"Selecting the INSTALL project and manually building it will copy the .dll and any other required files into the GUI's plugins directory. The next time you launch the GUI from Visual Studio, the Online PSTH plugin should be available."

Also small detail, when compiling the GUI, [this web page states](https://open-ephys.github.io/gui-docs/Developer-Guide/Compiling-the-GUI.html) to open the "open-ephys.sln" file in Visual Studio, in the build folder the only sln file was name open-ephys-GUI.sln.

**Comment by jsiegle** [comment]
Thanks for catching that error in the docs – I just fixed it!

To build the Release version of the plugin, first you'll have to build the main application in Release mode.

You may have to run INSTALL one more time to get the plugin to copy. If that doesn't work, you can search for the `online-psth.dll` file and copy that manually to the `plugins` directory alongside the Open Ephys executable.
