### ISSUE TITLE
Single trial or averaged?

### ISSUE THREAD

**Issue by guilhemibos** [open-ephys-plugins/online-psth#3]
Hello

I'm wondering whether the pluggin is plotting single trials only (complete refresh of the graphs on each trial) or whether it averaged over the different trials? I have the impression it's the first one but I'm not sure. If so, would it be possible to have a version which averages activities over the trials?
Thanks
Guilhem

**Comment by jsiegle** [comment]
The PSTH should be plotting averaged data. If you switch it to "Raster" mode, it will plot an event-aligned spike raster for individual trials. If this is not the behavior you're seeing, let us know.
